// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdKUUIn433SJFZZWbctoNHme6vx3HX0Ds',
    appId: '1:917848612255:web:d670729e36adb224f1f1aa',
    messagingSenderId: '917848612255',
    projectId: 'tropica-183da',
    authDomain: 'tropica-183da.firebaseapp.com',
    storageBucket: 'tropica-183da.firebasestorage.app',
    measurementId: 'G-BB30GEC2TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXUfpxTpmRxWblKe0G-Ogo3_uUDwBfOs',
    appId: '1:917848612255:android:c3518c7affb35fd9f1f1aa',
    messagingSenderId: '917848612255',
    projectId: 'tropica-183da',
    storageBucket: 'tropica-183da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSva8tCB2BoRsL1-10ZTaJZA6nt5Mfmxo',
    appId: '1:917848612255:ios:86a5749e8e355a62f1f1aa',
    messagingSenderId: '917848612255',
    projectId: 'tropica-183da',
    storageBucket: 'tropica-183da.firebasestorage.app',
    iosBundleId: 'com.example.tropicaguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSva8tCB2BoRsL1-10ZTaJZA6nt5Mfmxo',
    appId: '1:917848612255:ios:86a5749e8e355a62f1f1aa',
    messagingSenderId: '917848612255',
    projectId: 'tropica-183da',
    storageBucket: 'tropica-183da.firebasestorage.app',
    iosBundleId: 'com.example.tropicaguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdKUUIn433SJFZZWbctoNHme6vx3HX0Ds',
    appId: '1:917848612255:web:9091f4dd4f6f6766f1f1aa',
    messagingSenderId: '917848612255',
    projectId: 'tropica-183da',
    authDomain: 'tropica-183da.firebaseapp.com',
    storageBucket: 'tropica-183da.firebasestorage.app',
    measurementId: 'G-ZNXVNKSGQM',
  );

}